<!DOCTYPE html>
<html>
<head>
<title>Pillocate | Terms & Conditions</title>
<meta name="layout" content="pillocateLayout">

</head>

<body>
	<g:render template="/template/navigationConsumer" />

	<div class="container">
		<div class="row">
			<div class="col-md-10 col-md-offset-1">
				<g:form controller="feedback" action="sendFeedback" method="PUT">
					<div class="form-horizontal">
						<div class="panel panel-default order-panel">
							<div class="panel-heading text-center">Terms & Conditions</div>
							<div class="panel-body">

								<div>
									<p style="text-align: justify; font-weight: bold;">I2i
										Technology Solutions Private Limited</p>
									<p style="text-align: justify; font-weight: bold;">General
									</p>
									<p style="text-align: justify;">This document is an
										electronic record within the meaning of the Information
										Technology Act, 2000 and rules thereunder as applicable and
										the amended provisions pertaining to electronic records in
										various statutes, as amended by the Information Technology
										Act, 2000. This electronic record is generated by a computer
										system and does not require any physical or digital
										signatures.</p>
									<p style="text-align: justify;">The domain name
										www.pillocate.com (hereinafter referred to as "Website") is
										owned by i2i Technology Solutions Pvt Ltd with its registered
										office at Chennai.</p>
									<p style="text-align: justify;">Your use of the Website and
										services and tools are governed by the following terms and
										conditions ("Terms of Use") as applicable to the Website
										including the applicable policies which are incorporated
										herein by way of reference. If You transact on the Website,
										You shall be subject to the policies that are applicable to
										the Website for such transaction. By mere use of the Website,
										You are deemed to have read and agreed to these Terms of Use
										which, including the Privacy Policy and Dispute Resolution
										Policy, constitute Your binding obligations, with I2i.</p>
									<p style="text-align: justify;">This document is published
										in accordance with the provisions of Rule 3 (1) of the
										Information Technology (Intermediaries Guidelines) Rules, 2011
										that require publishing the rules and regulations, privacy
										policy and Terms of Use for access or usage of
										www.pillocate.com website.</p>
									<p style="text-align: justify;">For the purpose of these
										Terms of Use, wherever the context so requires "You" or "User"
										shall mean any natural or legal person who has agreed to
										become a provider or -/buyer on the Website by providing
										Registration Data while registering on the Website as
										Registered User using the computer systems.'I2i', ‘i2i’, 'We',
										'Our', 'Us' stands for i2i Technology Solutions Pvt Ltd.,</p>
									<p style="text-align: justify;">When You use any of the
										services provided by I2i through the Website, including but
										not limited to, (e.g. Product Reviews, Provider Reviews), You
										will be subject to the rules, guidelines, policies, terms, and
										conditions applicable to such service, including but not
										limited to the Privacy Policy and Dispute Resolution Policy,
										and they shall be deemed to be incorporated into this Terms of
										Use and shall be considered as part and parcel of this Terms
										of Use. We reserve the right, at Our sole discretion, to
										change, modify, add or remove portions of these Terms of Use,
										at any time without any prior written notice to You. It is
										Your responsibility to review these Terms of Use periodically
										for updates / changes. Your continued use of the Website
										following the posting of changes will mean that You accept and
										agree to the revisions. As long as You comply with these Terms
										of Use, We grant You a personal, non-exclusive,
										non-transferable, limited privilege to enter and use the
										Website. Throughout this Terms of Use, I2i's prior written
										consent means a communication coming from I2i's Legal
										Department, specifically in response to Your request, and
										specifically addressing the activity or conduct for which You
										seek authorization.</p>


									<p style="text-align: justify;">A.ELIGIBILITY</p>
									<p style="text-align: justify;">Use of the Website, either
										by registration or by any other means, is available only to
										persons, who are 18 years of age and above and persons who can
										enter into a legally binding contract, and or are not barred
										by any law for the time being in force. If you access I2i,
										either by registration on the Site or by any other means, not
										as an individual but on behalf of a legal entity, you
										represent that you are fully authorized to do so and the
										listing, posting or information placed on the site on behalf
										of the legal entity is your responsibility and you agree to be
										accountable for the same to other users of the Site. As a
										minor if you wish to use or transact on website, such use or
										transaction may be made by your legal guardian or parents on
										the Website. I2i reserves the right to terminate your
										membership and / or refuse to provide you with access to the
										Website if it is brought to I2i's notice or if it is
										discovered that you are under the age of 18 years.</p>
									<p style="text-align: justify;">B.RELEASE OF LIABILITY OF
										I2I:</p>
									<p style="text-align: justify;">1.All
										commercial/contractual terms are offered by and agreed to
										between Pharmacy and Buyers alone, in the absence of I2i as a
										party. The commercial/contractual terms include but are not
										limited to, price, shipping costs, deposit amounts, payment
										methods, payment terms, date, period and mode of delivery,
										warranties related to products. I2i does not have any control
										and does not determine or advise or in any way involve itself
										in the offering or acceptance of such commercial/contractual
										terms between the Pharmacy and Buyers.</p>
									<p style="text-align: justify;">2.I2i does not make any
										representation or Warranty as to specifics (such as quality,
										value, saleability, etc) of the products or services proposed
										to be sold/rented or offered to be sold or purchased or rented
										on the Website. I2i does not implicitly or explicitly support
										or endorse the sale or purchase or rent of any products or
										services on the Website. I2i accepts no liability for any
										errors or omissions, whether on behalf of itself or third
										parties.</p>
									<p style="text-align: justify;">4.I2i shall not at any time
										hold any right, title or interest over the products and/or
										services sold, purchased or rented on the Website nor shall
										I2i have any obligations or liabilities in respect of such
										contract entered into between Buyers and Providers. I2i is not
										responsible for unsatisfactory or delayed performance of
										services or damages or delays as a result of products which
										are out of stock, unavailable or back ordered.</p>
									<p style="text-align: justify;">5.You release and indemnify
										I2i and/or any of its officers and representatives from any
										cost, damage, liability or other consequence of any of the
										actions of the Users of the Website and specifically and
										explicitly waive any claims that you may have in this behalf
										under any applicable law. Notwithstanding its reasonable
										efforts in that behalf, I2i cannot take responsibility or
										control the information provided by other Users which is made
										available on the Website. You may find other User's
										information to be offensive, harmful, inconsistent,
										inaccurate, or deceptive. Please use caution and practice safe
										trading when using the Website. Please note that there could
										be risks in dealing with underage persons or people acting
										under false pretence.</p>
									<p style="text-align: justify;">6.You also agree that I2i
										is not responsible or liable for any loss suffered due to
										damage caused to the product or reduction of value of the
										product in any way.</p>
									<p style="text-align: justify;">D.CONTENT ON THE WEBSITE</p>
									<p style="text-align: justify;">1.The Website contains
										content which includes Your Information, I2i’s information and
										Information from other users. You agree not to copy, modify,
										or distribute such content (other than Your Information),
										I2i’s copyrights or trademarks. When You give us any content
										as part of Your Information, you are granting us a
										non-exclusive, worldwide, perpetual, irrevocable,
										royalty-free, sub-licensable right and license to use,
										reproduce, , publish, translate, distribute, perform and
										display such content (in whole or part) worldwide through the
										Website as well as on any of our affiliates or partners
										websites, publications and mobile platform. </p>
									<p style="text-align: justify;">2.I2i shall have the right
										to remove or edit any content that in its sole discretion
										violates, or is alleged to violate, any applicable law or
										either the spirit or letter of these Terms of Use.
										Notwithstanding this right, You remain solely responsible for
										the content of the materials you post on the website and in
										your private messages. Please be advised that such Content
										posted does not necessarily reflect I2i views. In no event
										shall I2i assume or have any responsibility or liability for
										any Content posted or for any claims, damages or losses
										resulting from use of Content and/or appearance of Content on
										the Website.</p>
									<p style="text-align: justify;">3.You agree that in the
										event your listing, posting or your information violates any
										provision of this Terms of Use, I2i shall have the right to
										terminate and or suspend your membership of the Website and
										refuse to provide you or any person acting on your behalf,
										access to the Website.</p>

									<p style="text-align: justify;">E.ROLE OF I2I</p>
									<p style="text-align: justify;">1.As a registered Pharmacy,
										you are allowed to list items for rent or sale to other Users
										on the Website in accordance with the Terms of Use, Privacy
										Policy and Dispute Resolution Policy. You must be legally able
										to rent and sell the item(s) you list for sale on I2i. You
										must ensure that the listed items do not infringe upon the
										intellectual property, trade secret or other proprietary
										rights or rights of publicity or privacy rights of third
										parties.</p>
									<p style="text-align: justify;">2.The description of the
										item must not be misleading or inaccurate and must describe
										the true and actual condition of the product. If the item
										description does not match the actual condition of the item,
										you agree to refund any amounts that you may have received
										from the - or Buyer. You agree not to list a single product in
										multiple quantities across various categories on the Website.
										I2i reserves the right to delete such multiple listings of the
										same product listed by you in various categories.</p>
									<p style="text-align: justify;">3. You, as a registered
										Pharmacy, are under an obligation to maintain a true and
										accurate inventory of the products available.</p>
									<p style="text-align: justify;">4.Transactions, Transaction
										Price and all commercial terms such as Delivery, Dispatch of
										products and/or services are as per principal to principal
										bipartite contractual obligations between Buyer and Pharmacy
										and payment facility is merely used by the Buyer and Pharmacy
										to facilitate the completion of the Transaction. Use of the
										payment facility shall not render I2i liable or responsible
										for the non-delivery, non-receipt, non-payment, damage, breach
										of representations and warranties, non-provision of after
										sales or warranty services or fraud as regards the products
										listed on I2i's Website.</p>
									<p style="text-align: justify;">5.You have specifically
										authorized I2i or its service providers to collect, process,
										facilitate and remit payments and / or the Transaction Price
										electronically or through Cash on Delivery to and from other
										Users in respect of transactions through Payment Facility.
										Your relationship with I2i is on a principal to principal
										basis and by accepting these Terms of Use you agree that I2i
										is an independent contractor for all purposes, and does not
										assume control of or liability for the products or services
										that are listed on I2i's Website that are paid for by using
										the Payment Facility. I2i does not guarantee the identity of
										any User nor does it ensure that a Buyer or a Pharmacy will
										complete a transaction.</p>
									<p style="text-align: justify;">6.You understand, accept
										and agree that the payment facility provided by I2i is neither
										a banking nor financial service but is merely a facilitator
										providing an electronic, automated online electronic payment,
										receiving payment through Cash On Delivery, collection and
										remittance facility for the Transactions on the I2i Website
										using the existing authorized banking infrastructure and
										Credit Card payment gateway networks. Further, by providing
										Payment Facility, I2i is neither acting as trustee nor acting
										in a fiduciary capacity with respect to the Transaction or the
										Transaction Price.</p>
									<p style="text-align: justify;">7.You understand, accept
										and agree that I2i has the obligation to pay the money
										collected under the Payment Facility, within 15 days from the
										date on which the money becomes payable to you, in accordance
										with the terms of the transaction you have with the other
										User.</p>

									<p style="text-align: justify;">F.INDEMNITY</p>
									<p style="text-align: justify;">You agree to indemnify and
										hold I2i, its officers, subsidiaries, affiliates, successors,
										assigns, directors, officers, agents, service providers,
										suppliers and employees, harmless from any claim or demand,
										including reasonable attorney fees and court costs, made by
										any third party due to or arising out of content submitted by
										the User, User’s use of the service, violation of the Terms of
										Use, breach by the User of any of the representations and
										warranties herein, or the User’s violation of any rights of
										any other party.</p>
									<p style="text-align: justify;">G.APPLICABLE LAW</p>
									<p style="text-align: justify;">These Terms of Use shall be
										governed by and interpreted and construed in accordance with
										the laws of India. The Courts in Chennai shall have exclusive
										jurisdiction over any disputes arising out of the Terms of
										Use.</p>
									<p style="text-align: justify;">H.TRANSACTIONS IN INDIA
										ONLY</p>
									<p style="text-align: justify;">Unless otherwise specified,
										the material on the Website is presented solely for the
										purpose of rent/sale in India. I2i makes no representation
										that materials in the Website are appropriate or available for
										use in other locations/Countries other than India. Those who
										choose to access this site from other locations/Countries
										other than India do so on their own risk and I2i is not
										responsible for supply of products/refund for the products
										ordered from other locations/Countries other than India,
										compliance with local laws, if and to the extent local laws
										are applicable.</p>
									<p style="text-align: justify;">I.ENTIRE AGREEMENT</p>
									<p style="text-align: justify;">1. This Terms of Use
										constitutes the entire and whole agreement between You and
										I2i, and is intended as a complete and exclusive statement of
										the terms of the agreement. This agreement shall supersede all
										other communications between I2i and its users with respect to
										the subject matter hereof and supersedes and replaces all
										prior or contemporaneous understandings or agreements, written
										or oral, regarding such subject matter. If at any time you
										find these Terms of Use unacceptable or if you do not agree to
										these Terms of Use, please do not use this Website. We may
										revise these Terms of Use at any time without notice to you.
										It is your responsibility to review these Terms of Use
										periodically.</p>
									<p style="text-align: justify;">2. Nothing contained in
										this clause will affect the applicability and binding nature
										of the provisions of the Privacy Policy and Dispute Resolution
										Policy.</p>
									<p style="text-align: justify;">3. These Terms, and any
										rights and licenses granted hereunder, may not be transferred
										or assigned by you, but may be assigned by I2i without
										restriction. Any assignment or transfer by you shall be null
										and void.</p>
									<p style="text-align: justify;">J.SEVERABILITY OF
										PROVISIONS</p>
									<p style="text-align: justify;">The Terms of Use, Privacy
										Policy and Dispute Resolution Policy constitute the entire
										agreement with respect to the use of the service provided by
										I2i. If any provision of these terms and conditions is
										unlawful, void or unenforceable then that provision shall be
										deemed severable from the remaining provisions and shall not
										affect their validity and enforceability.</p>
									<p style="text-align: justify;">K.TRADEMARK, COPYRIGHT AND
										RESTRICTION</p>
									<p style="text-align: justify;">This site is controlled and
										operated by I2i and products are rented/sold by respective
										Pharmacy. All material on this site, including images,
										illustrations, audio clips, and video clips, are protected by
										copyrights, trademarks, and other intellectual property
										rights. Material on Website is solely for Your personal,
										non-commercial use.</p>
									<p style="text-align: justify;">L.LIMITATION OF LIABILITY</p>
									<p style="text-align: justify;">In no event shall I2i be
										liable for any special, incidental, indirect or consequential
										damages of any kind in connection with these Terms of Use even
										if the User has been informed in advance of the possibility of
										such damages.</p>
									<br />
								</div>




							</div>
							<div class="panel-footer clearfix">
								<div class="row">
									<%--                       <div class="col-sm-offset-4 col-xs-12 col-sm-3">--%>
									<%--                        <button type="submit" class="btn btn-primary btn-block"><i class="glyphicon glyphicon-ok"></i>&nbsp; Submit</button>--%>
									<%--                       </div>--%>
								</div>
							</div>
						</div>
					</div>
				</g:form>
			</div>
		</div>
	</div>

</body>
</html>
